version: '2'

services:
  postgres:
    image: 'postgres:12.2'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5434:5434'

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "coinlogic.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/coinlogic'
    ports:
      - '8000:8000'

volumes:
  postgres:
